name: task_10
description: Background Services

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0


dev_dependencies:
  freezed: ^2.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

