name: task_10
description: Background Services

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  awesome_notifications: ^0.7.4+1

flutter_native_splash:
  color: "#b6c1fd"
  color-dark: "#b6c1fd"
  image: assets/icons/alarm-icon.png
  image-dark: assets/icons/alarm-icon.png
  android_12:
    image-dark: assets/icons/alarm-icon.png
    image: assets/icons/alarm-icon.png
    color: "#b6c1fd"
    color-dark: "#b6c1fd"
    icon_background_color_dark: "#b6c1fd"
    icon_background_color: "#b6c1fd"
  ios: true
  android: true
dev_dependencies:
  freezed: ^2.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/icons/'
    - 'assets/icons/2x/'
    - 'assets/icons/3x/'
    - 'assets/icons/4x/'
    - 'assets/images/svgs/'
